/// <reference types="expo/types" />

// This file is generated by Expo projects and is intentionally kept in source control
// so editors can resolve Expo's environment types before the first native build.
